import Link from "next/link";

export const metadata = {
  title: "Terms of Service | WorkZo AI",
  description: "WorkZo AI Terms of Service",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-canvas px-5 py-10 text-fg">
      <div className="mx-auto max-w-4xl">
        <div className="mb-8 flex items-center justify-between gap-4">
          <Link href="/" className="text-sm font-bold text-brand hover:text-brand">
            ← Back to Home
          </Link>
          <Link href="/dashboard" className="rounded-xl bg-brand px-4 py-2 text-sm font-black text-on-brand hover:bg-brand">
            Dashboard
          </Link>
        </div>

        <section className="rounded-3xl border border-line bg-fg/[0.04] p-6 shadow-[0_24px_90px_rgba(0,0,0,0.35)] sm:p-8">
          <p className="text-xs font-black uppercase tracking-[0.25em] text-brand">Legal</p>
          <h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Terms of Service</h1>
          <p className="mt-3 text-sm leading-6 text-muted">
            Last updated: June 2026
          </p>

          <div className="mt-8 space-y-7 text-sm leading-7 text-muted">
            <section>
              <h2 className="text-lg font-black text-fg">1. About WorkZo AI</h2>
              <p className="mt-2">
                WorkZo AI provides AI-powered career preparation tools, including resume analysis, interview practice,
                job preparation support, and related career guidance features.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-fg">2. No Employment Guarantee</h2>
              <p className="mt-2">
                WorkZo AI does not guarantee job offers, interviews, hiring decisions, salary outcomes, visa outcomes,
                or employer responses. The platform is intended to support preparation and learning.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-fg">3. User Responsibility</h2>
              <p className="mt-2">
                You are responsible for reviewing and verifying any resume, cover letter, interview response, or career
                recommendation generated by WorkZo AI before using it externally.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-fg">4. AI-Generated Content</h2>
              <p className="mt-2">
                AI-generated outputs may contain mistakes, incomplete information, or wording that may not fit every
                situation. Users should treat the output as a helpful draft or preparation aid, not as professional legal,
                immigration, tax, financial, or employment advice.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-fg">5. Acceptable Use</h2>
              <p className="mt-2">
                You agree not to misuse WorkZo AI, attempt to disrupt the service, upload harmful content, violate third-party
                rights, or use the platform for illegal, deceptive, or abusive purposes.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-fg">6. Privacy</h2>
              <p className="mt-2">
                Use of WorkZo AI is also governed by our Privacy Policy. Please review it to understand how data may be
                processed while using the platform.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-black text-fg">7. Changes to Terms</h2>
              <p className="mt-2">
                We may update these terms from time to time. Continued use of WorkZo AI after changes means you accept
                the updated terms.
              </p>
            </section>
          </div>
        </section>
      </div>
    </main>
  );
}
