import type { Metadata } from "next";
import { ShieldCheck, Server, Database, Trash2, FileCheck2, Mic } from "lucide-react";
import { MarketingShell, Reveal, Eyebrow, SectionHeading, BackLink } from "@/components/marketing/kit";

export const metadata: Metadata = {
  title: "Security & Data Handling, WorkZo AI",
  description:
    "How WorkZo AI stores, processes, and protects candidate data: infrastructure, subprocessors, voice recordings, retention, and GDPR rights.",
};

/**
 * Honest, plain-language security page for B2B/education buyers. Rule: only
 * state what is true today. No certifications we don't hold, no "bank-grade"
 * language. Update the subprocessor list whenever a provider is added or
 * removed, an outdated subprocessor list is a GDPR problem, not a cosmetic
 * one.
 */

const SUBPROCESSORS: Array<{ name: string; purpose: string; region: string }> = [
  { name: "Supabase", purpose: "Database, authentication, and file storage", region: "EU (Frankfurt)" },
  { name: "Vercel", purpose: "Application hosting and delivery", region: "Global edge, EU processing available" },
  { name: "Stripe", purpose: "Payments and billing", region: "EU/US (PCI-DSS Level 1)" },
  { name: "OpenRouter / Google / OpenAI", purpose: "AI language models for interview questions and feedback", region: "EU/US" },
  { name: "Vapi", purpose: "Real-time voice interview infrastructure", region: "US/EU" },
  { name: "ElevenLabs", purpose: "Recruiter voice synthesis", region: "US/EU" },
  { name: "Tavus", purpose: "AI video avatars (Premium Pro only)", region: "US" },
  { name: "Resend", purpose: "Transactional email", region: "US/EU" },
  { name: "Sentry", purpose: "Error monitoring (no CV contents in reports)", region: "EU available" },
];

const PRACTICES = [
  {
    icon: Database,
    title: "Where your data lives",
    text: "Account data, interview history, and parsed CV profiles are stored in Supabase (PostgreSQL) with row-level security, so each user can only access their own records. Payments are handled entirely by Stripe, we never see or store card numbers.",
  },
  {
    icon: Mic,
    title: "Voice and interview data",
    text: "Voice interviews are processed in real time to power the conversation. Transcripts are stored with your interview history so you can review feedback. CV files you upload are parsed into a structured profile; the profile drives your interviews and can be replaced by uploading a new CV at any time.",
  },
  {
    icon: ShieldCheck,
    title: "AI processing",
    text: "Interview questions and feedback are generated by AI models via the subprocessors listed below. CV and interview content is sent to these providers only to run your sessions, we do not sell data, and we do not use your CV to train our own models.",
  },
  {
    icon: Trash2,
    title: "Deletion and your rights",
    text: "You can request deletion of your account and all associated data at any time via the Delete My Data page or by emailing support@workzoai.com. Under GDPR you also have the right to access, correct, and export your data.",
  },
  {
    icon: Server,
    title: "Access control",
    text: "Production access is limited to the founder. Administrative endpoints are authenticated, partner analytics use scoped, signed access keys, and internal tooling is not exposed in production.",
  },
  {
    icon: FileCheck2,
    title: "For institutions",
    text: "We are a young company and honest about our maturity: we do not yet hold SOC 2 or ISO 27001 certification. We are happy to complete your security questionnaire, sign a data processing agreement (DPA/AVV), and walk your DPO through our data flows before any pilot.",
  },
];

export default function SecurityPage() {
  return (
    <MarketingShell>
      <div className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8">
        <BackLink href="/">Back home</BackLink>
      </div>

      <section className="mx-auto max-w-4xl px-4 pb-8 pt-8 sm:px-6 lg:px-8">
        <Reveal>
          <Eyebrow icon={ShieldCheck}>Security &amp; data</Eyebrow>
          <h1 className="mt-5 text-4xl font-black leading-[1.05] tracking-tight sm:text-5xl">
            How we handle your data
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-muted">
            Interview practice involves sensitive material: your CV, your voice, your performance. This page explains
            plainly where that data goes, who processes it, and what control you keep. Questions your security team
            can&apos;t answer here, we&apos;ll answer directly:{" "}
            <a href="mailto:support@workzoai.com" className="underline">support@workzoai.com</a>.
          </p>
        </Reveal>
      </section>

      <section className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
        <div className="grid gap-5 sm:grid-cols-2">
          {PRACTICES.map((item) => (
            <Reveal key={item.title}>
              <div className="h-full rounded-xl border border-line bg-surface/70 p-6">
                <item.icon className="h-5 w-5 text-brand" />
                <h2 className="mt-3 text-base font-black text-fg">{item.title}</h2>
                <p className="mt-2 text-sm leading-6 text-muted">{item.text}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      <section className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
        <SectionHeading
          eyebrow="Subprocessors"
          title="Who processes data on our behalf"
          intro="Each provider receives only the data required for its purpose. This list is kept current; if it changes, this page changes."
        />
        <div className="mt-8 overflow-hidden rounded-xl border border-line">
          {SUBPROCESSORS.map((sp, i) => (
            <div
              key={sp.name}
              className={`grid gap-1 px-5 py-4 sm:grid-cols-[180px_1fr_220px] sm:items-center ${i % 2 ? "bg-canvas-soft/60" : "bg-surface/50"}`}
            >
              <div className="text-sm font-black text-fg">{sp.name}</div>
              <div className="text-sm leading-6 text-muted">{sp.purpose}</div>
              <div className="text-xs font-black uppercase tracking-[0.12em] text-muted sm:text-right">{sp.region}</div>
            </div>
          ))}
        </div>
        <p className="mt-6 text-sm leading-6 text-muted">
          Need a signed data processing agreement (DPA/AVV), a subprocessor notification commitment, or a completed
          security questionnaire for procurement? Email{" "}
          <a href="mailto:support@workzoai.com?subject=DPA%20request" className="underline">support@workzoai.com</a>{" "}
         , turnaround is a few business days, not weeks.
        </p>
      </section>
    </MarketingShell>
  );
}
